mjordan/islandora_workbench

.gitignore
workbench

- Partially resolve #121
- Update gitigore to include some build directories

Remove stray else statement.

---

README.md

Just a suggestion. "Anyone can edit" feels a bit dangerous as a setting on a spreadsheet that can override your metadata, so if it isn't necessary, I'd keep it out of the readme.

Small readme change for Google instructions

---

workbench_utils.py

Addresses issue 218
(also changed line 2792 to be windows-friendly)

added option to auto-delete tmp files

---

workbench_utils.py

https://github.com/mjordan/islandora_workbench/issues/276
Checks for duplicate column headers
Added an inline check
Run a --check on a csv with duplicate headers.  You should be notified.
@mjordan_
---

added check for duplicate column headers

---

workbench_utils.py

>  Allows for additional files to be added to the sanity check
>  Added an extra condition to column header check
> Try the --check on a config with additional files
>  @mjordan_
---

added additional file check

---

workbench
workbench_fields.py

Enables entity reference fields that refer to media (by mid)
four lines added parallel to  how this works for nodes
Does it work?
Hope you're not looking at this on vacation @mjordan
---

Add support for media entity reference fields.

---

WorkbenchConfig.py
setup.py
workbench
workbench_utils.py

> **[Issue 376](https://github.com/mjordan/islandora_workbench/issues/376)** -
> Moves configuration manipulation to a single class, for ease or readability and maintainability
> Logic was moved from the workbench_utils class to WorkbenchConfig
> Try running any config that has worked for you in the past, with and without `--check`
The results should be identical.
@mjordan 
---

Moved config manipulation to a single class.

---

workbench

> [Issue 338](https://github.com/mjordan/islandora_workbench/issues/383)
> Prevents the same term being added duplicated on update.
> Added a few filters.
> Create an update task that adds a new term.  Run it a few times.  The new term should only show up once.
> @mjordan
---

prevents multiple inclusions of identical terms

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

#399
This PR fixes a handful of misspelled words using the aspell CLI spell checker.
A few words had their spelling fixed.
Using this workflow...
https://islandora-collaboration-group.github.io/ISLE/contributor-docs/spell-checker/
Raed over test and make sure the new spelling is correct for the context.
@mjordan
---
Not applicable.

Fixes a couple of misspellings

---

Dockerfile
README.md

Adding this so I don't forget. 
This is a Dockerfile to allow the Python dependencies to be isolated into a single container to run. 
This should simplify the running but needs work and documentation.

Add Dockerfile as an option to run

---

workbench_utils.py

> **[Issue 497](https://github.com/mjordan/islandora_workbench/issues/497)** 
> _**Removes tmp directories**_
> _**Added a flag to `get_preprocessed_file_path`** - subdirectory will only be created if required._
> _**Ingest remote files from a worksheet, with`delete_tmp_upload: true` set in the config file.  All temp directories should be gone when the job completes**_
> _**@mjordan**_
---

added directory creation flag

---

Dockerfile

Improves the docs and build process.
N/A
Improves the Dockerfile's build process and refines the in-code docs. 
Runs the setup.py within the image and sets the working directory so that when running the container it automatically drops the user into the directory where workbench is located. 
Docs should make it easier to use and understand.
Removed a typo.
Run the 2 lines in the inline docs at the top of the file.
@mjordan 
---

Removes a few steps from the container start

---

workbench_fields.py

Address 553.

---

workbench_utils.py

#626 
Closes #626 
Changes line 3348 in `workbench_utils.py` to `media_endpoint_path = '/entity/media?_format=json' if config['standalone_media_url']  else '/entity/media'`
N/A
@mjordan_
---

Address #626

---

workbench_utils.py

Closes #629.
Performs the changes outlined in #629
Please see #629
N/A
@mjordan 
---

Address Issue #629

---

workbench_fields.py

Closes #635 
Fix a KeyError caused by not checking existence of a key prior to access.
Check for existence first.
N/A
@mjordan_
---

Resolve #635

---

.github/workflows/build.yml

This addresses https://github.com/mjordan/islandora_workbench/issues/652 
This PR adds a github workflow for that will create binaries for workbench and attach them to a release when it is created.
See a test release https://github.com/willtp87/islandora_workbench/releases/tag/0.0.9
@mjordan 
---

Binaries added to releases.

---

workbench_utils.py

> #664
Allows media types to set a default status/published value,  making them compatible with Workflows.
Docs will be updated this evening.

Address #664.

---

workbench_utils.py

#220 
This PR adds NumPy style docstrings to a couple of functions.
I reformatted pre-existing comments summarizing what a ew functions accomplished, then added some NumPy style function docstrings that matched the style that the code base was already using.
Here is an example of this style...
``
def set_media_type(config, filepath, file_fieldname, csv_row):
"""Using either the 'media_type' or 'media_types_override' configuration
setting, determine which media bundle type to use.
Parameters
----------
config : dict
The configuration settings defined by workbench_config.get_config().
filepath: string
The value of the CSV 'file' column.
file_fieldname: string
The name of the CSV column containing the filename (usually 'file').
csv_row : OrderedDict
The CSV row for the current item.
Returns …

First attempt in adding NumPy style docstrings

---

i7Import/configs/islandora7_import_sample.config
i7Import/i7ImportUtilities.py

> **Adds some Solr query options** 
> **Added the ability to change start row and the number of lines to retrieve, as well as the ability to select a number of collections from which o draw results** 
> **Make a config file with a start row other than 0, rows anything other than the default 100,000, and an array of collections from which to draw results** 
> _**@mjordan**
---

added some optional solr parameters

---

i7Import/get_islandora_7_content.py
i7Import/i7ImportUtilities.py

> _**Makes SSL requirements configurable;** -
> _**Added a new config with a sensible default**
> _**Run a harvest with secure_ssl_only=False in the config file** 
> _**@mjordan @rosiel ** - name some folks who may be interested, or, if unsure, @mjordan_
---

allowed i7 harvesting without checking certs

---

workbench_utils.py

In response to #831 - just a typo fix.

PR for fifileeld_name typo

---

workbench
workbench_utils.py

https://github.com/mjordan/islandora_workbench/issues/880
Allows paragraphs in create_ and update_ modes.

Patch for #880

---

workbench_utils.py

Related to #924 
Implements the user_agent config in `check_file_exists()` 
Just adding the header for User-Agent to maintain consistency with other requests.
Set a value for the `user_agent` config and observe the logs of a server when `check_file_exists` is called.
@mjordan  @dara2
---

Use user_agent for check_file_exists

---

tests/field_tests.py
workbench
workbench_fields.py
workbench_utils.py

Resolves: #921 
* Adds a `WorkbenchFields` class to act as the base class of all the various field classes.
* De-duplicates code where easily possible
* Adds a factory class to return the correct field based on the `field_type` to avoid requiring changing other files to handle new fields.
Creates a `WorkbenchFields` class with the base methods, then make all the existing fields extend this class. Allow similar code to reside in the super class.
Because there were several fields that had identical `create` methods except for each using their own string splitting function, I added `def split_string(config: dict, value: str)` so each field can override this to allow for their differences.
I also noticed you needed to change code in 4 places across 2 files, so I added a simple factory class …

Inheritance

---

tests/islandora_tests_check.py

Possibly related to this https://github.com/mjordan/islandora_workbench/issues/561
Fixes typo in assertRegex assertions. They will never pass as written.
These tests should never pass, even locally so if they are there are larger issues.
@mjordan
---

Typo in assertion
