workbench, workbench_utils.py
Issue: #66
Oh, hey! I already did have a fork I can issue PRs from setup. Okay.
This PR includes the base fields for the configured content type to `get_field_definitions(config)` so that workbench can push up things like the node's 'Published' status.
=> add support for base fields

workbench_utils.py
> **https://github.com/mjordan/islandora_workbench/issues/262** 
> Allows media to upload via Drupal REST endpoint
> Added format
> Create a media with workbench using a Drupal 8 instance (don't know if this fix is necessary for 9)
>  @mjordan @dara virks
---
=> added format to fix file uploads

workbench_utils.py
[## Link to Github issue](https://github.com/mjordan/islandora_workbench/issues/279)
Allows unweighted compound ingests to pass validation
A CSV with parent_id doesn't need a field_weight to work.  This changes validation
Removed a single condition, updated inline comments, add a notice if field_weight was missing
Run a CSV with parent_id as a column header but now field_weight.  Test to see that ingest still works
@mjordan_
---
=> updated validation

workbench_utils.py
https://github.com/mjordan/islandora_workbench/issues/343
Checks the config setting about changing the media name to the node name before doing so. 
This changes default behaviour: with the same (default) config, the media will now have the filenames as the media names.
Check whether the 'use_node_title_for_media' config parameter is set. It's False by default. If it's set to true, then use the node name as the media name.
Ingest nodes and files. The media (especially if you have additional_files) will all be named same as the node.
With this PR, they will be named per their original filenames.
> _**Replace this text** - name some folks who may be interested, or, if unsure, @mjordan_
---
=> Use filename for media_name unless config otherwise.

workbench
> Allows the updating of typed_relations with missing terms in current node
> Added a test to see if term exists before attempting to resave
> Create node with linked agents pointing to a saved term.  Delete that term,  Verify that your node still tries to reference that missing term.
> Create Update task to insert new values for `field_linked_agent` 
> Run batch job and check for success.
> @mjordan
---
=> added checks for missing terms

workbench_utils.py
[Issue 334](https://github.com/mjordan/islandora_workbench/issues/334)
Allows additions and overrides for media type to extension mapping.  Note that type assignment happens _after_ the defaults have been evaluated, meaning defaults can be left intact.
Added `media_type_override` to config
Add the following to your config file
```
media_types_override:
- custom: ['png', 'jpg']
- custom2: ['pdf', 'txt']
```
Workbench will now fail by trying to assign one of two fictitious media types
@mjordan
---
=> added media types override

workbench_utils.py
> **[Issue 375 - adds content type check](https://github.com/mjordan/islandora_workbench/issues/375)** 
> notifies user if the chosen content type does not exist on their Drupal installation
> Added a function to check for content type, and then runs that check before we attempt to grab fields
> Create a config with a bogus content type and try to use it.  You should get an error
>  @mjordan
---
=> Added content type check

workbench_utils.py
> [Issue 391](https://github.com/mjordan/islandora_workbench/issues/391)
> Allows function to be called with missing parameter
> Added default
> Run any csv with both local and remote files using --check
No startlement should occur.
> @mjordan_
---
=> Added default value

workbench, workbench_utils.py
#310 & #434
Adds fixes for the `allow_missing_files: true` and `additional_files` to work as expected.
- Shifts the `additional_files` check out of the `files` check so it can be run alone.
- Adds two `allow_missing_files` to the `--check` so it doesn't fail early.
- Clean-up some issues identified by my IDE.
Set up a create task config similar to
```yml
task: create
host: "http://dams.library.unlv.edu"
username: REDACTED
password: 'REDACTED'
input_dir: 'O:\digitalworkspace\MAN Manuscript Collections'
input_csv: MS-00169.csv 
allow_missing_files: true
content_type: dc_object
id_field: field_digital_id
additional_files:
- service: 139
```
where some rows are missing any file references and some rows have no file path in the file field but a file path in the additional_files column.
Running …
=> Additional Files fixes

workbench
#436
This adds the ability to provide view parameters for the get_data_from_view task.
Adds a new view_parameters variable to get_data_from_view that will pull from a view_parameters array in the config and then modifies the view_url to incorporate them into each request.
1. Create a REST view and workbench config according to [the instructions](https://mjordan.github.io/islandora_workbench_docs/generating_csv_files/#using-a-drupal-view-to-identify-content-to-export-as-csv). 
2. Add a Filter to the REST view and set it to be exposed. E.g. 
3. Add a view_parameters config that includes a line for the value you want in the exposed filter. E.g.
```yml
view_parameters:
- 'field_digital_id_value=whh'
```
4. Run the task and note that it pulled in records that match the configured filter. …
=> Issue #436: add view_parameters config for get_data_from_view

setup.py
Add empty modules list.
https://github.com/mjordan/islandora_workbench/issues/447
Issue in other project with resolution : https://github.com/pypa/setuptools/issues/3197#issuecomment-1078770109
Fix setup.py to run on newer versions of Python / setup tools.
Add an empty list of modules in setup.py to avoid error about multiple directories.
On macOS Home-brew, the current version is 3.9.13. Clone the repository, and test as per the installation instructions.
> _**Replace this text** - name some folks who may be interested, or, if unsure, @mjordan_
---
* [ N/A] Have you included same configuration and/or CSV files useful for testing this PR?
* [ N/A] Have you written unit or integration tests if applicable?
* [ N/A] If the changes in this PR require an additional Python library, have you …
=> Issue 447:  setup.py not working on macOS / Homebrew

workbench
I noticed two lines that can cause crashes because `logging.info.warning(message)` should have been `logging.warning(message)`.
(None)
Bug fix
All `logging.info.warning(message)` lines were changed to `logging.warning(message)`.
N/A
@mjordan
---
=> Changed logging.info.warning to logging.warning

workbench_utils.py
> **[Issue 543](https://github.com/mjordan/islandora_workbench/issues/543)** 
> **Adds explicit error message when taxonomy terms require namespace**
> **Message and exit** 
> **Test by putting an un-namespaced term in a spreadsheet for a field which allows multiple taxonomies. The program should exit with a meaningful message.** 
> **@mjordan**
---
=> Added explicit error message

WorkbenchConfig.py, workbench_utils.py
(None)
Added a configuration option to specify what directory to store the rollback CSV in. This was created in response to a use case where the `input_dir` only had read permission, but it could have other uses.
Added `rollback_dir` as a configuration option. It defaults to `None`, in which `get_rollback_csv_filepath` will use `input_dir` instead, following old behavior.
In addition, it now provides an error message within `prep_rollback_csv` if it fails to write to the rollback CSV for any reason, which should catch majority of rollback file permission issues.
(Plus one bonus bugfix.)
Run a task with an `input_dir` that only has read permissions. Then add a `rollback_dir` with write permissions and run the task again.
@mjordan
---
=> Added rollback_dir configuration option

setup.py
Got burned by [this](https://islandora.slack.com/archives/C01TLCB0EEQ/p1683127763076039) today on a Playbook build. 
@mjordan @rosiel
=> Pin ruamel.yaml to 0.17.21 or below.

workbench_fields.py
https://github.com/mjordan/islandora_workbench/issues/604
Serialized links will not include `%%` if the `title` field is an empty string.
Most of our Digital Collections objects' permalinks have a null title:
`"field_archival_resource_key":[{"uri":"http:\/\/n2t.net\/ark:\/62930\/d1j09wb2f","title":null,"options":[]}]`,
but for an unknown reason, some of them have an empty title:
`"field_archival_resource_key":[{"uri":"http:\/\/n2t.net\/ark:\/62930\/d1sw7m","title":"","options":[]}]`,
which is then serialized as `http://n2t.net/ark:/62930/d1sw7m%%`.
I figured that it is safe to simply exclude the `%%` in such cases.
Added a simple check for empty titles.
Export metadata for some objects with links that have empty titles as well as ones with links that have null titles.
@mjordan_
=> Changed LinkField to not append %% for empty titles

workbench_utils.py
(None)
Bug fix
Swapped order of error checking to avoid a Python `UnboundLocalError`.
(In the case that `file_id` is `None`, the variable `file_response` is never initialized.)
Run a `delete_media` task in which one of the medias fails to find a file_id (I don't know how to easily replicate this).
@mjordan_
---
=> Fixed crash in remove_media_and_file when file_id cannot be found

workbench_utils.py
> **Issue #252**
> This fixes the issue with remote video media.
> Two lines in the create media function where file_results get compared. It now does not change the remote video media url.
> To test you need a remote video file from Youtube or Vimeo. Use the add_media task and include the oembed_provders. The csv file only needs at minimum the node_id and file columns. 
Sample Data:
<!DOCTYPE html>
<html>
<body>
node_id | file
-- | --
14 | https://vimeo.com/video_id_number
</body>
</html>
Sample Configuration File:
task: add_media
host: "https://islandora.traefik.me"
username:
password:
input_dir: remote_video
input_csv: remote_video.csv
oembed_providers:
\- remote_video: ['https://vimeo.com/', 'https://www.youtube.com/']
> _**Replace this text** - name some folks who may be interested, …
=> Changed file_result comparison

workbench_utils.py
#633 
Fixes an exception when a `--check` is run against a CSV with a `created` field and a row with an invalid date
Added the `config` variable to a method call to fixe `NameError: name 'config' is not defined` error
Issue #633 contains a test CSV.
```
id,parent_id,field_member_of,url_alias,title,field_model,field_resource_type,file,field_display_hints,created
collection:8001,,,/islandora/object/collection:8001,Test Collection: Delete,Collection,Collection,,,1-1-1
```
The config file is a basic `create`
```
task: create
host: "https://islandora.dev"
username: 
password: 
input_dir: /tmp
input_csv: z.csv
output_csv: z.output
allow_adding_terms: true
allow_missing_files: true
timestamp_rollback: true
log_response_body: false
```
```
./workbench --config /tmp/test.yaml --check
```
---
=> Fixes exception when `created` is an invalid date; #633

WorkbenchConfig.py, workbench_utils.py
Solution for https://github.com/mjordan/islandora_workbench/issues/620
Refactors work in progress from #268 to use new `perform_soft_checks` variable
Allows `soft_checks` for `--check` errors that should really be handled in batches, rather than having the check fail on every instance. Initial implementation includes:
* Parent/child order issues
* File extension checks
* EDTF date validation
And it refactors the old `strict_check` to now use `perform_soft_checks`. The logic for variable checking has been reversed, since semantically the two config variables mean the opposite.
* Added a new config `'perform_soft_checks': True`
* Added three uses of that variable to allow skipping `exit` functions 
* Refactors `strict_check` to `perform_soft_checks`
* Check out this branch and run a test …
=> implementing soft_checks for #620

workbench
https://github.com/mjordan/islandora_workbench/issues/640
Fixes a syntax error caused by variable name error
Two variable replacements
You really have to be able to trigger this `if` statement to get the error
```
if config['paged_content_from_directories'] is True:
create_children_from_directory(config, row_as_parent, node_id)
```
@mjordan
=> Fix for #640 variable name issue

workbench
=> Discard expired cache items for #632

workbench_utils.py
#665
Puts in a tiny fix for the use of basename().
A single instance of `basename()` was changed to use `os.path.basename()`.
This appears to be a simple syntax error. 
Though to test the PR you would need to trigger the `create()` function in `workbench_utils.py` while your `input.csv` does not have a "title" field defined. 
@mjordan
---
=> Small change of syntax to fix issue

workbench_utils.py
#657 
Switching to a python best practice of not using mutable types in default function params
The function params with mutable default values were set to `None`, then inside the function body the params/variables were properly set with their respective mutable type. 
Run some workbench tasks that send REST calls to Drupal to see if the change works.
@mjordan_
---
* [ x] Before opening this PR, have you opened an issue explaining what you want to to do?
* [ x] Have you run `pycodestyle --show-source --show-pep8 --ignore=E402,W504 --max-line-length=200 yourfile.py`?
=> Remove mutable params

workbench, workbench_utils.py
> [Issue #661](https://github.com/mjordan/islandora_workbench/issues/661)
> Fixes string literal error for term_id in update_terms.
> Converts int returned by find_term_in_vocab to a string. This was causing errors in the requests because an int was being used in string concatenations.
> <blockquote>
<p dir="auto">To test, you need a csv file with term_id. All other columns are the same as what you would use for create_terms, however, term_name is not used as a lookup value for the term id and only used if you want to change the term name. To change the parent reference to root, value must be 0. The configuration file needs the task update_terms and vocab_id. The term_id and parent can either be string or numeric. The sample data below updates Notated movement term''s reference from …
=> Convert int to string to avoid errors with requests

workbench_utils.py
* #682 
Entity reference fields were getting overridden by their "Simple Field" values. This stops doing that.
'if' -> 'elif' 
Before this PR: replicate the bug in #682 
With this PR: terms (and other entities) are exported as values (id or name) in the export spreadsheet.
@mjordan 
---
=> Export entity reference fields properly.

tests/assets/WorkbenchConfig_test/config_01_create_short_valid.yml, tests/assets/WorkbenchConfig_test/config_02_01_create_short_invalid.yml, tests/assets/WorkbenchConfig_test/config_02_02_create_short_invalid.yml, tests/assets/WorkbenchConfig_test/config_02_03_create_short_invalid.yml, tests/unit_tests_workbench_config.py
#445 
Adds a few unit tests using the Python built-in`unittest` module to WorkbenchConfig.py
New unit test file added called `tests/unit_tests_workbench_config.py` but it may make sense to integrate the unit tests into a pre-existing existing unitest file. 
Also added some test config.yml files in:
tests/assets/WorkbenchConfig_test
There might be a better approach to test WorkbenchConfig.py that having several different config files, but this seems like a good starting point. We may want to come up with a standardized way to name the test config files.
Write now my unittest code works with this execution syntax:
python3 -m unittest -v tests/unit_tests_workbench_config.py
NOTE:  I will make changes so that in the future my test(s) works with the syntax used for other isladnora_workbench …
=> First attempt at adding unit tests to WorkbenchConfig.py [WIP]

workbench, workbench_utils.py
* address https://github.com/mjordan/islandora_workbench/issues/703
* Addresses a code path during the create workflow that will skip the creation of the URL alias in Drupal
* Addresses 'TypeError: can only concatenate str (not "int") to str' if preexisting URL alias exists on the Drupal site
* Also, rollback config .yml creation was being skipped
* Moves the code block that creates the URL Alias to a location above the a code block containing a `continue`  statement thus skipping the URL Alias creation. The code block: https://github.com/mjordan/islandora_workbench/blob/f41fa85b0afac02c9a6adc9d92c1a8355624f8cd/workbench#L318-L322
* create an input CSV with the required fields, a specified `url_alias`, plus and empty `file` field (for example, a collection node)
* Workbench config: …
=> Fixes skipped URL alias additions when "file" field is unspecified

workbench_utils.py
https://github.com/mjordan/islandora_workbench/issues/719
Sets the response to stream so we can use [iter_content](https://requests.readthedocs.io/en/latest/api/#requests.Response.iter_content) to read/write the response
> When stream=True is set on the request, this avoids reading the content at once into memory for large responses. 
Also, turns off caching responses via `requests_cache` for files downloaded.
> _**Replace this text** - State clearly the direct additions or modifications made in this pull request._
Use workbench to load a large file into your i2 repo
@ajstanley 
---
=> Use streamed response for file downloads

workbench_utils.py
With @rosiel 
When checking to make sure the media with media tracks is a Service File, only check if media tracks are present in that row.
I indented lines 5070-5108 by one indent (four spaces).
Test with a spreadsheet like that in [Islandora Demo Objects](https://github.com/Islandora-Devops/islandora_demo_objects/blob/main/create_islandora_objects.csv), which has a column for media tracks, but some rows do not have a media track and are  `http://pcdm.org/use#ThumbnailImage` (or anything other than `http://pcdm.org/use#ServiceFile`). Run workbench with the `--check` option.
Before this, check will fail.
After this, check will pass.
@mjordan_
---
=> Only check media track row if media track is present.

.github/workflows/black.yml, workbench
https://github.com/mjordan/islandora_workbench/pull/744
https://github.com/mjordan/islandora_workbench/pull/744 neglected to lint `./workbench`. This PR corrects that.
Run `black` against `./workbench` as well as all other python files
Check the GHA actions.
@mjordan 
---
=> Include workbench file when linting in GHA

workbench_fields.py
https://github.com/mjordan/islandora_workbench/issues/755
Simplifies the field definition implementations.
- The fields definitions were checking if a sub-delimiter existed in the CSV cell and calling two separate pieces of logic in the case of existing or not existing. That can be simplified by always splitting on the sub-delimiter and handling the values that way: https://github.com/mjordan/islandora_workbench/pull/754/commits/df1df23210149021d8d3b734229984552284fb6f
- Similarly, the cardinality handling of limited vs unlimited can be simplified by handling unlimited and limited in the same `if` conditional: https://github.com/mjordan/islandora_workbench/pull/754/commits/cca4d9466827c5f60096b002ed3ac235dab5cd68
```
if -1 < cardinality < len(subvalues)
// remove additional values over …
```
=> Refactor fields sub-delimiter and cardinality handling

workbench_fields.py
Works with both `None` values and empty strings.
Fix for https://islandora.slack.com/archives/C01TLCB0EEQ/p1715094887941549
Fixes issue where empty values caused taxonomy lookups to throw errors resulting in failed entity reference revisions updates.
`s#if row[field_name] is None#if not row[field_name]#`
See linked Slack conversation above.
@mjordan,  Dara Virks, and @dmer
---
=> Make empty field checks pythonic

Dockerfile
> [Issue #814](https://github.com/mjordan/islandora_workbench/issues/814) - Improve Dockerfile to Handle Permissions (run as non-root user) and Enhance Build Compatibility.
> [PR #18](https://github.com/mjordan/islandora_workbench_docs/pull/18) - Add docs for using Dockerfile
> This PR enhances the existing Dockerfile by addressing build warning issues that were confusing when running building the container. It also optimizes the build process and improves compatibility with different host environments by aligning user and group IDs inside the container with those on the host system.
> - **User and Group ID Handling**: Introduced build arguments `USER_ID` and `GROUP_ID` to ensure the Docker container runs with the same user and group IDs as the host, preventing permission issues when …
=> Addressing compatibility and remove DOCKER_BUILDKIT in the Docker setup

Dockerfile
https://github.com/mjordan/islandora_workbench/issues/814
Add's Noah's suggestion of using variables to chown the workbench directory
updated dockerfile to use $USER_ID and $GROUP_ID variables
Without this PR, building fails on MacOS. Testing should include building on Mac and Linux
@noahwsmith @DonRichards @mjordan 
---
=> Update Dockerfile to work with MacOS

setup.py
> _**Issue** - https://github.com/mjordan/islandora_workbench/issues/822
> _**Replace this text** - Remove pyparsing pre-release version
> _**Replace this text** - State clearly the direct additions or modifications made in this pull request._
Python version: 3.8.19
> _**install dependencies** - python setup.py install
> _**run tests** - python tests/unit_tests.py
> @mjordan_
---
=> fix: resolve Python 3.8 CI pipeline failures #822.

i7Import/get_islandora_7_content.py
The index should always be set, because it will be accessed later in the script and generate a runtime error
Sets the index variable to the config's id_start_number, even if id_field was already in the header
When each row is iterated later on in the script, index will be accessed. If it is not set, a runtime error occurs. 
```
if config["id_field"] in headers:
row[config["id_field"]] = index + reader.line_num - 2
```
=> Always set index

WorkbenchConfig.py, i7Import/i7ImportUtilities.py, tests/assets/set_media_type_test/multi_types_config.yml, workbench_utils.py
> **[Addresses issue 836](https://github.com/mjordan/islandora_workbench/issues/836)**
> **Allows definition of media types** 
> **Added and implemented  media_type_by_media_use config** 
(also threw in a parameter to allow harvesting i7 data from a list of PIDS)
> **add this to config if additional fields have been defined.  Test files should now be of correct media type** 
```
media_type_by_media_use:
- https://projects.iq.harvard.edu/fits: fits_technical_metadata
```
```
additional_files:
- extracted: http://pcdm.org/use#ExtractedText
- fits: https://projects.iq.harvard.edu/fits
- service: http://pcdm.org/use#ServiceFile
- thumbnail: http://pcdm.org/use#ThumbnailImage
```
-
> ** @mjordan** 
---
=> added override to assign media types by media use

i7Import/i7ImportUtilities.py
#911 
If not in the user provided configuration you get a `KeyError`
Added to the default configuration
Make a simple PR, using the example in i7Import/configs/islandora7_import_sample.config
Try to run an i7 export, see
```bash
> python3 i7Import/get_islandora_7_content.py --config islandora7_export.config.yml 
Processing 100.
Traceback (most recent call last):
File "/Users/jaredwhiklo/www/DAM2/islandora_workbench/i7Import/get_islandora_7_content.py", line 96, in <module>
if row["PID"] in config["pids_to_skip"]:
KeyError: 'pids_to_skip'
```
With this PR and no changes to your config. See it not fail.
@mjordan
---
=> Add pids_to_skip to i7ImportUtilities

scripts/make_local_tests.py
Resolved #918 
Replaces the password only from the end of the string, instead of the start.
Run a command like
```bash
python3 scripts/make_local_tests.py --host https://jared.uri --username test_username --password somePassword
```
Then check one of the configuration files changed and in the `tests_local` directory, (i.e. `tests_local/assets/check_test/delete.yml`)
```yaml
task: delete
host: https://jared.uri
username: test_username
somePassword: somePassword
input_csv: delete.csv
secure_ssl_only: false
```
Pull in this PR, re-run `make_local_tests.py` command and check the file again
```yaml
task: delete
host: https://jared.uri
username: test_username
password: somePassword
input_csv: delete.csv
secure_ssl_only: false
```
@mjordan
---
=> Fix password string replacement

tests/unit_tests.py
#937 
Renames some test assets so that macOS users will not be warned about file name collisions when cloning the repository, and so that unit tests pass when run locally with act.
Also avoids the test assets files being lost when a macOS user makes a pull request.
Altered test assets and unit test file to avoid file name collisions on case-insensitive filesystems.
Unit tests should pass
Specifically when run on a macOS using act
@mjordan 
* [Y ] Before opening this PR, have you opened an issue explaining what you want to to do?
* [N/A ] Have you included some configuration and/or CSV files useful for testing this PR?
* [ Y] Have you written unit or integration tests if applicable?
* [ N] Does the code added in this PR require a version of Python that is higher than the current minimum …
=> 937 Alter tests to support case insensitive filesystems

workbench_fields.py
Check the entity type of a referenced object before trying to ping it.
#946 
This change means that when the workbench_fields.py::serialize() function is called, it will no longer try to ping a node's Id as if it were a taxonomy term. This would succeed much of the time due to overlap of the Nid with an unrelated Tid.
In workbench_fields.py::serialize, added extra checks for if the entity being referenced is a term or a node and calls the appropriate ping_* function depending on which one it is.
Also adds a fallback for any other type of entity where the id is included without trying to ping any URL.  
From a fresh Islandora Starter Site, load the Islandora Demo Objects.
```shell
python3 ../islandora_workbench/workbench --config create_islandora_objects.yml
```
Then check out the main …
=> Fix for #946: export_csv task drops some field_member_of values

Makefile
This MR adds a Makefile which gives a single command which allows islandora_workbench to be spun up in Docker instead of run locally. This gets around local Python issues, etc.
To test, you must have Docker installed and then you can run `run-workbench-in-docker`. 
You can also run `make build-islandora-workbench` to build the image, but that's a dependency of the above, so it should happen automatically. If you change git commit on your local, it will automatically know to do a rebuild. If for whatever reason you have to force a rebuild, run `make rebuild-islandora-workbench`.
=> adding a Makefile to make running in docker easier

tests/field_tests.py, workbench, workbench_fields.py
Resolves #929 
Makes it possible to ingest objects with a `linked_data_field`.
This work is based off of changes made #922, so it will need to be rebased once that is incorporated. Or feel free to rewrite this using the existing structure. I'll leave it as a draft for now.
Adds a new class `LinkedDataField` that uses existing `LinkField` field class as its parent. 
It overrides to alter the string splitting and serialization to handle the different JSON dictionary keys.
I copied all the existing `LinkField` unit tests and altered to test the new class.
I've also tested this locally. I set up a `linked_data_field` called `field_linked_subjects` in my Drupal.
Then I added a column to my spreadsheet with that name and some values from LoC using the same format as the Link fields.
``` …
```
=> Linked data field

WorkbenchConfig.py
https://github.com/mjordan/islandora_workbench/issues/969
Print more details about YAML errors in the passed config.yml file.
I am grabbing details from the raised YAMLError exception and printing them to the CLI.
I am attaching an example config.yml file that is an RTF/plaintext hybrid, but it has been renamed to config.txt to allow me to upload it to the issue.
[config_rtf_plaintext_hybrid.txt](https://github.com/user-attachments/files/20746513/config_rtf_plaintext_hybrid.txt)
@mjordan
---
=> Print out additional YAML exception error info from get_user_config()
